<?php

declare(strict_types=1);

namespace App\Modules\Access\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\PermissionRegistrar;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

final class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'dashboard.view',
            'profile.view',
            'audit_log.view_any',
            'users.view',
            'users.manage',
            'roles.view',
            'roles.manage',
            'cities.view_any',
            'cities.manage',
            'objects.view_any',
            'objects.manage',
            'employees.view_any',
            'employees.manage',
            'positions.manage',
            'directories.view_any',
            'directories.manage',
            'organizations.view_any',
            'organizations.manage',
            'welds.view_any',
            'welds.manage',
            'ndt_requests.view_any',
            'ndt_requests.manage',
            'ndt_tasks.view_any',
            'ndt_tasks.manage',
            'ndt_results.view_any',
            'ndt_results.manage',
            'ndt_results.analyze',
            'ndt_results.approve',
            'conclusions.view_any',
            'conclusions.manage',
            'conclusions.version',
            'conclusions.approve',
            'conclusions.issue',
            'conclusions.replace',
            'conclusions.annul',
            'registers.view_any',
            'registers.manage',
            'registers.transfer',
            'registers.archive',
            'registers.act',
            'radiography.view_any',
            'radiography.manage',
            'shifts.view_any',
            'shifts.manage',
            'inventory.manage',
            'equipment.view_any',
            'equipment.manage',
            'weld_ndt_methods.manage',
            'document.view_any',
            'document.manage',
            'file.create',
            'file.download',
            'file.delete',
        ];

        foreach ($permissions as $permissionName) {
            Permission::findOrCreate($permissionName, 'web');
        }

        $rolePermissions = [
            'Администратор системы' => $permissions,
            'Начальник участка' => [
                'dashboard.view',
                'profile.view',
                'objects.view_any',
                'employees.view_any',
                'organizations.view_any',
                'organizations.manage',
                'welds.view_any',
                'welds.manage',
                'ndt_requests.view_any',
                'ndt_requests.manage',
                'ndt_tasks.view_any',
                'ndt_tasks.manage',
                'ndt_results.view_any',
                'ndt_results.manage',
                'ndt_results.analyze',
                'ndt_results.approve',
                'conclusions.view_any',
                'conclusions.manage',
                'conclusions.version',
                'conclusions.approve',
                'conclusions.issue',
                'conclusions.replace',
                'conclusions.annul',
                'registers.view_any',
                'registers.manage',
                'registers.transfer',
                'registers.archive',
                'registers.act',
                'shifts.view_any',
                'shifts.manage',
                'inventory.manage',
                'equipment.view_any',
                'equipment.manage',
                'weld_ndt_methods.manage',
                'document.view_any',
                'document.manage',
                'file.create',
                'file.download',
                'file.delete',
            ],
            'Инженер НК / Дешифровщик' => [
                'dashboard.view',
                'profile.view',
                'organizations.view_any',
                'welds.view_any',
                'ndt_requests.view_any',
                'ndt_tasks.view_any',
                'ndt_results.view_any',
                'ndt_results.manage',
                'ndt_results.analyze',
                'conclusions.view_any',
                'conclusions.manage',
                'conclusions.version',
                'conclusions.replace',
                'registers.view_any',
                'registers.manage',
                'registers.transfer',
                'registers.archive',
                'registers.act',
                'radiography.view_any',
                'radiography.manage',
                'shifts.view_any',
                'shifts.manage',
                'equipment.view_any',
                'document.view_any',
                'file.create',
                'file.download',
            ],
            'Дефектоскопист' => [
                'dashboard.view',
                'profile.view',
                'organizations.view_any',
                'welds.view_any',
                'ndt_requests.view_any',
                'ndt_tasks.view_any',
                'ndt_results.view_any',
                'ndt_results.manage',
                'registers.view_any',
                'registers.manage',
                'registers.transfer',
                'registers.archive',
                'radiography.view_any',
                'radiography.manage',
                'shifts.view_any',
                'shifts.manage',
                'inventory.manage',
                'equipment.view_any',
                'document.view_any',
                'file.download',
            ],
            'Лаборант' => [
                'dashboard.view',
                'profile.view',
                'organizations.view_any',
                'welds.view_any',
                'ndt_requests.view_any',
                'ndt_tasks.view_any',
                'ndt_results.view_any',
                'conclusions.view_any',
                'registers.view_any',
                'registers.manage',
                'registers.transfer',
                'registers.archive',
                'radiography.view_any',
                'radiography.manage',
                'shifts.view_any',
                'shifts.manage',
                'inventory.manage',
                'equipment.view_any',
                'document.view_any',
                'file.create',
                'file.download',
            ],
        ];

        foreach ($rolePermissions as $roleName => $permissionNames) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->syncPermissions($permissionNames);
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
